  local options = {
    -- ...others options...
    showmode = false,          -- we don't need show mode because we see in the lualine statusline (Insert, Visual, etc)
    -- ...others options...
  }
